"""user

Revision ID: 23c7adf5c5d2
Revises: edd6c7d8db0a
Create Date: 2024-09-29 22:32:54.640218

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "23c7adf5c5d2"
down_revision: Union[str, None] = "edd6c7d8db0a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "User", sa.Column("is_superuser", sa.Boolean(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("User", "is_superuser")
    # ### end Alembic commands ###
