"""add adress

Revision ID: bb249c032dee
Revises: b806960d33d6
Create Date: 2024-10-07 19:51:08.629916

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "bb249c032dee"
down_revision: Union[str, None] = "b806960d33d6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("Post")
    op.add_column("User", sa.Column("adress", sa.String(), nullable=True))
    op.drop_index("idx_users_email", table_name="User")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index("idx_users_email", "User", ["email"], unique=False)
    op.drop_column("User", "adress")
    op.create_table(
        "Post",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "title", sa.VARCHAR(length=255), autoincrement=False, nullable=True
        ),
        sa.Column(
            "content",
            sa.VARCHAR(length=255),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "is_published", sa.BOOLEAN(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "author_id", sa.INTEGER(), autoincrement=False, nullable=True
        ),
        sa.Column("likes", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["author_id"], ["User.id"], name="Post_author_id_fkey"
        ),
        sa.PrimaryKeyConstraint("id", name="Post_pkey"),
    )
    # ### end Alembic commands ###
